// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GameManager.Models;

public partial class Game
{
    public int PkGameId { get; set; }

    public int FkGameTypeId { get; set; }

    public int FkDayOfWeek { get; set; }

    public TimeSpan StartTime { get; set; }

    public TimeSpan EndTime { get; set; }

    public int MaxPlayers { get; set; }

    public int Gm { get; set; }

    public virtual DaysOfWeek FkDayOfWeekNavigation { get; set; }

    public virtual GameType FkGameType { get; set; }

    public virtual Player GmNavigation { get; set; }
}