// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GameManager.Models;

public partial class GamePlayer
{
    public int FkGameId { get; set; }

    public int FkPlayerId { get; set; }

    public int FkGamePlayerStatusId { get; set; }

    public DateTime RequestDt { get; set; }

    public DateTime JoinDt { get; set; }

    public virtual Game FkGame { get; set; }

    public virtual GamePlayerStatus FkGamePlayerStatus { get; set; }

    public virtual Player FkPlayer { get; set; }
}